### ISSUE TITLE
Using Redvox python sdk to locate a sound source

### ISSUE THREAD

**Issue by chrisvwn** [RedVoxInc/redvox-python-sdk#19]
This is not really an issue. Rather a question on possible uses.

Is it possible to use the redvox python sdk to locate a sound? For example if there is a known frequency that is constantly playing and I have 3 android devices running the software and recording, would it be possible to use the timestamped data to get a good estimate of the bearing or location of the sound source?

**Comment by tylerty04** [comment]
It sounds like you need to apply the physics and mathematics necessary to solve your equation for locating the sound.  The SDK just provides the data for you to analyze/process.
